# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Colors' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Colors
  pod 'Alamofire'
  target 'ColorsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ColorsUITests' do
    # Pods for testing
  end

end
